/**
 * All Action Keys
 */

// SignIn
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const SET_SIGNIN = 'SET_SIGNIN';

//SignUp
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

//Webinars
export const GET_ALL_WEBINARS_REQUEST = 'GET_ALL_WEBINARS_REQUEST';
export const GET_ALL_WEBINARS_SUCCESS = 'GET_ALL_WEBINARS_SUCCESS';
export const GET_ALL_WEBINARS_ERROR = 'GET_ALL_WEBINARS_ERROR';

//Webinar
export const GET_WEBINAR_INFO_REQUEST = 'GET_WEBINAR_INFO_REQUEST';
export const GET_WEBINAR_INFO_SUCCESS = 'GET_WEBINAR_INFO_SUCCESS';
export const GET_WEBINAR_INFO_ERROR = 'GET_WEBINAR_INFO_ERROR';

//Courses
export const GET_ALL_COURSES_REQUEST = 'GET_ALL_COURSES_REQUEST';
export const GET_ALL_COURSES_SUCCESS = 'GET_ALL_COURSES_SUCCESS';
export const GET_ALL_COURSES_ERROR = 'GET_ALL_COURSES_ERROR';

//Course
export const GET_COURSE_INFO_REQUEST = 'GET_COURSE_INFO_REQUEST';
export const GET_COURSE_INFO_SUCCESS = 'GET_COURSE_INFO_SUCCESS';
export const GET_COURSE_INFO_ERROR = 'GET_COURSE_INFO_ERROR';

//Profile
export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR';

//Profile-Update
export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_ERROR = 'UPDATE_USER_PROFILE_ERROR';

//Forgot
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

//Verify-Mobile
export const VERIFY_MOBILE_REQUEST = 'VERIFY_MOBILE_REQUEST';
export const VERIFY_MOBILE_SUCCESS = 'VERIFY_MOBILE_SUCCESS';
export const VERIFY_MOBILE_ERROR = 'VERIFY_MOBILE_ERROR';

//Exams
export const GET_EXAMS_REQUEST = 'GET_EXAMS_REQUEST';
export const GET_EXAMS_SUCCESS = 'GET_EXAMS_SUCCESS';
export const GET_EXAMS_ERROR = 'GET_EXAMS_ERROR';

//Packs
export const GET_PACKS_REQUEST = 'GET_PACKS_REQUEST';
export const GET_PACKS_SUCCESS = 'GET_PACKS_SUCCESS';
export const GET_PACKS_ERROR = 'GET_PACKS_ERROR';

//Single Pack Info
export const GET_PACK_REQUEST = 'GET_PACK_REQUEST';
export const GET_PACK_SUCCESS = 'GET_PACK_SUCCESS';
export const GET_PACK_ERROR = 'GET_PACK_ERROR';
