const CONSTANT = {
  createAccountText: 'Create an account',
  signUpToYourAccountText: 'Sign Up to your account',
  schoolStudentText: 'School Student',
  schoolStudentText1: 'SCHOOL_STUDENT',
  collegeStudentText: 'College Student',
  collegeStudentText1: 'COLLEGE_STUDENT',
  facultyWorkingProfStartupText: 'Faculty/Working Professional/Startup',
  StudentNameText: 'Student Name',
  enterEmailText: 'Enter Email',
  phoneNumberText: 'Phone Number',
  organisationNameText: 'Organisation Name',
  alredyHaveAnAccountText: 'Already have an account?',
  signInText: ' Sign In',
  signUpText: 'Sign Up',
  collegeUniversityText: 'College/University',
  studentTypes: [
    'School Student',
    'College Student',
    'Faculty/Working Professional/Startup',
  ],
  welcomeBackText: 'Welcome Back',
  loginToYourAccountText: 'Login to your account',
  mobileNumberText: 'Mobile No',
  forgotYourPasswordText: 'Forgot your password?',
  dontHaveAnAccountText: "Don't have an account?",
  loginText: ' Login',
  forgotPasswordText: 'Forgot Password',
  pleaseEnterMobileNumberText:
    'Please enter your mobile number to \n receive a verification code.',
  sendText: 'Send',
  backToLoginText: 'Back to login',
  verifyYourMobileText: 'Verify Your Mobile',
  pleaseEnter4DigitCodeText: 'Please enter the 4 digit code sent to',
  resendCodeText: 'Resend code',
  verifyText: 'Verify',
  pleaseEnterAllDigitText: 'Please enter all digit',
  indiasBiggestText: "INDIA's Biggest",
  ipOlympiadExamText: 'IP Olympiad Exam',
  studentRegisteredText: '1250 students registered',
  enrollNowText: 'Enroll Now',
  connectVPNinEasySteps: 'Connect VPN in 5 easy steps',
  megaMockChallenge: 'Mega Mock Challenge',
  realTimeExamExperienceText: 'Real Time Exam Experience',
  iptseAssessmentExamText: 'IPTSE assessment exam',
  registerText: 'Register',
  dateText: 'Date',
  invoiceText: 'Invoice',
  amountText: 'Amount',
  gstText: 'GST(4%)',
  totalText: 'Total',
  statusText: 'Status',
  logOutText: 'Log Out',
  saveChangesText: 'Save Changes',
  nameText: 'name',
  emailText: 'email',
  phoneText: 'phone',
  universityText: 'university',
  viewAllText: 'View All >',
  upcomingWebinarsText: 'Upcoming Webinars',
  readingBooksText: 'Reading Books',
  earnCertificateAfterCompletionText: 'Earn free certificate after completion',
  details: 'Details',
  continueReadingText: 'Continue Reading',
  buyForText: 'Buy for INR {rs}',
  viewDetailsText: 'View Details',
};
export default CONSTANT;
