import {StyleSheet, Dimensions} from 'react-native';
import {
  FontFamily,
  normalizeFontSize,
  normalizeSize,
} from '../../../utils/util';
import COLOR from '../../../utils/color';
const {width} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    width: normalizeSize(width * 0.9, 'width'),
    borderRadius: normalizeSize(10, 'width'),
    backgroundColor: COLOR.white,
    alignItems: 'flex-start',
    paddingBottom: normalizeSize(20, 'height'),
    elevation: 4,
  },
  mainContainer: {
    width: normalizeSize(width * 0.9, 'width'),
    borderRadius: normalizeSize(10, 'width'),
    backgroundColor: COLOR.white,
    alignItems: 'flex-start',
    paddingBottom: normalizeSize(20, 'height'),
    elevation: 4,
    alignSelf: 'center',
  },
  courseContainer: {
    width: normalizeSize(width * 0.9, 'width'),
    borderRadius: normalizeSize(10, 'width'),
    backgroundColor: COLOR.white,
    alignItems: 'flex-start',
    paddingBottom: normalizeSize(20, 'height'),
    alignSelf: 'center',
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  headerContainer: {
    width: '90%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'center',
    marginVertical: normalizeSize(10),
  },
  imageContainer: {
    width: normalizeSize(width * 0.8, 'width'),
    borderRadius: normalizeSize(10, 'width'),
    backgroundColor: COLOR.orange,
    paddingVertical: normalizeSize(20, 'height'),
    elevation: 1,
  },
  timeContainer: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    paddingStart: normalizeSize(10, 'width'),
    marginTop: normalizeSize(15, 'height'),
    // backgroundColor: COLOR.red,
    backgroundColor: COLOR.white,
  },
  buttonContainer: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    paddingStart: normalizeSize(10, 'width'),
    marginTop: normalizeSize(15, 'height'),
  },
  inProgressViewContainer: {
    width: '100%',
    marginVertical: normalizeSize(8),
  },
  baseProgressContainer: {
    width: '50%',
    height: 4,
    borderRadius: normalizeSize(4),
    backgroundColor: COLOR.gray1,
    marginHorizontal: normalizeSize(10),
  },
  progressContainer: {
    position: 'absolute',
    width: '10%',
    height: 4,
    borderRadius: normalizeSize(4),
    backgroundColor: COLOR.orange,
  },
  infoContainer: {
    flexDirection: 'row',
    width: '100%',
    // alignItems: 'flex-start',
    // justifyContent: 'flex-start',
    // paddingStart: normalizeSize(10, 'width'),
    // marginTop: normalizeSize(15, 'height'),
    backgroundColor: COLOR.white,
  },
  infoLeftContainer: {
    width: '60%',
    // alignItems: 'flex-start',
    // justifyContent: 'flex-start',
    // paddingStart: normalizeSize(10, 'width'),
    // marginTop: normalizeSize(15, 'height'),
  },
  infoRightContainer: {
    width: '40%',
    // alignItems: 'flex-start',
    // justifyContent: 'flex-start',
    // paddingStart: normalizeSize(10, 'width'),
    // marginTop: normalizeSize(15, 'height'),
  },
  text: {
    fontFamily: FontFamily.MilliardSemiBold,
    color: COLOR.black,
    fontSize: normalizeFontSize(16),
    marginTop: normalizeSize(15, 'height'),
    paddingStart: normalizeSize(10, 'width'),
  },
  text1: {
    fontFamily: FontFamily.MilliardMedium,
    color: COLOR.black,
    fontSize: normalizeFontSize(14),
  },
  text2: {
    fontFamily: FontFamily.MilliardLight,
    color: COLOR.gray0,
    fontSize: normalizeFontSize(16),
    marginBottom: normalizeSize(10, 'height'),
  },
  text3: {
    fontFamily: FontFamily.MilliardMedium,
    color: COLOR.gray0,
    fontSize: normalizeFontSize(14),
  },
  text4: {
    fontFamily: FontFamily.MilliardLight,
    color: COLOR.gray0,
    fontSize: normalizeFontSize(12),
    paddingHorizontal: normalizeSize(10),
    paddingVertical: normalizeSize(8),
  },
  text5: {
    fontFamily: FontFamily.MilliardLight,
    color: COLOR.orange,
    fontSize: normalizeFontSize(12),
  },
  text6: {
    fontFamily: FontFamily.MilliardMedium,
    color: COLOR.orange,
    fontSize: normalizeFontSize(16),
  },
  image: {
    width: '100%',
    height: normalizeSize(160, 'height'),
    resizeMode: 'cover',
    backgroundColor: COLOR.orange,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    // alignSelf: 'flex-end',
  },
  image1: {
    width: '90%',
    height: normalizeSize(160, 'height'),
    resizeMode: 'cover',
    backgroundColor: COLOR.orange,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    alignSelf: 'center',
    // alignSelf: 'flex-end',
  },
  book: {
    width: normalizeSize(20),
    height: normalizeSize(20),
  },
  button: {
    width: normalizeSize(width * 0.3, 'width'),
    paddingVertical: normalizeSize(10, 'height'),
    alignSelf: 'flex-start',
    marginTop: normalizeSize(20, 'height'),
  },
  button1: {
    backgroundColor: COLOR.white,
    borderWidth: 1,
    borderColor: COLOR.orange,
  },
  separator: {
    height: normalizeSize(20, 'height'),
  },
});

export default styles;
